import UserTemplate from "@/components/userTemplate"
import UserList from "../../userList"

export const metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <UserTemplate title="Home" id="home" menuList={UserList}>
            {children}
        </UserTemplate>
    )
}

export default RootLayout